<?php
// This file is automatically generated. Do not edit manually.
return array(
	' requires %sAffiliateWP%s. Please activate it to continue.' => ' az %sAffiliateWP%s szükséges. A folytatáshoz aktiválja.',
	' requires %sAffiliateWP%s. Please install it to continue.' => ' az %sAffiliateWP%s szükséges. A folytatáshoz telepítse.',
	'Amount' => 'Összeg',
	'Cheatin&#8217; huh?' => 'Csalnál&#8217; mi?',
	'Coupon Code' => 'Kuponkód',
	'Coupons' => 'Kuponok',
	'Get add-ons' => 'Kiegészítők beszerzése',
	'Get more add-ons for AffiliateWP' => 'További kiegészítők beszerzése az AffiliateWP-hez',
	'There are currently no discount codes to display.' => 'Jelenleg nincsenek megjeleníthető kuponkódok.',
	'This plugin' => 'Ez a bővítmény',
);
