name: JSON Lint Check

on:
  push:
    branches:
      - main
    paths:
      - '**/*.json'
      - '!package.json'
      - '!package-lock.json'
  pull_request:
    paths:
      - '**/*.json'
      - '!package.json'
      - '!package-lock.json'
  workflow_dispatch:

jobs:
  json-lint:
    runs-on: ubuntu-latest

    name: JSON Lint Check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check JSON syntax
        run: |
          echo "🔍 Checking JSON syntax for all translation .json files..."

          # Find all JSON files except package.json and package-lock.json
          find . -name "*.json" \
            -not -path "./node_modules/*" \
            -not -path "./vendor/*" \
            -not -name "package.json" \
            -not -name "package-lock.json" | while read file; do

            echo "Checking: $file"

            # Use Node.js to validate JSON syntax
            node -e "
              const fs = require('fs');
              try {
                const content = fs.readFileSync('$file', 'utf8');
                JSON.parse(content);
                console.log('✓ Valid JSON');
              } catch (error) {
                console.error('✗ JSON parsing error:', error.message);
                process.exit(1);
              }
            "

            if [ $? -ne 0 ]; then
              echo "❌ Lint error in: $file"
              exit 1
            fi
          done

          echo "✅ All JSON files passed lint check!"

      - name: Validate translation JSON structure
        run: |
          echo "🔍 Validating translation JSON structure..."

          # Find all translation JSON files (in plugins/themes directories)
          find plugins themes -name "*.json" 2>/dev/null | while read file; do
            echo "Validating structure: $file"

            # Check if JSON has expected translation structure
            node -e "
              const fs = require('fs');
              try {
                const content = fs.readFileSync('$file', 'utf8');
                const data = JSON.parse(content);

                // Translation JSON files should be objects with string values
                if (typeof data !== 'object' || data === null) {
                  console.error('✗ Translation file must be a JSON object');
                  process.exit(1);
                }

                // Check if it has the expected structure (domain, locale_data, etc.)
                // Translation files typically have these keys or are flat key-value pairs
                console.log('✓ Valid translation structure');
              } catch (error) {
                console.error('✗ Structure validation error:', error.message);
                process.exit(1);
              }
            "

            if [ $? -ne 0 ]; then
              echo "❌ Invalid structure in: $file"
              exit 1
            fi
          done

          echo "✅ All translation JSON files have valid structure!"
