name: PHP Syntax Check

on:
  push:
    branches:
      - main
    paths:
      - '**/*.php'
  pull_request:
    paths:
      - '**/*.php'
  workflow_dispatch:

jobs:
  php-syntax:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2', '8.3']

    name: PHP ${{ matrix.php-version }} Syntax Check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Check PHP syntax
        run: |
          echo "🔍 Checking PHP syntax for all .php files..."
          find . -name "*.php" -not -path "./node_modules/*" -not -path "./vendor/*" | while read file; do
            echo "Checking: $file"
            php -l "$file"
            if [ $? -ne 0 ]; then
              echo "❌ Syntax error in: $file"
              exit 1
            fi
          done
          echo "✅ All PHP files passed syntax check!"

      - name: Validate L10N.php files structure
        if: matrix.php-version == '8.3'
        run: |
          echo "🔍 Validating L10N.php file structure..."
          find . -name "*.l10n.php" -not -path "./node_modules/*" | while read file; do
            echo "Validating: $file"

            # Check if file returns an array
            php -r "
              \$result = include '$file';
              if (!is_array(\$result)) {
                echo 'Error: File must return an array\n';
                exit(1);
              }
              echo 'Valid array structure\n';
            "

            if [ $? -ne 0 ]; then
              echo "❌ Invalid structure in: $file"
              exit 1
            fi
          done
          echo "✅ All L10N.php files have valid structure!"
